KERNEL_SIZE: 10
image_size: [256, 256, 3]
primary_samples: 2
backup_samples: 8
num_epochs: 2001
densification_interval: 100
learning_rate: 0.01
image_file_name: "Image-01.png"
display_interval: 5
gradient_threshold: 0.002
gaussian_threshold: 0.05
display_loss: False
